services:
  dexlot-bot-prod:
    image: dexlot-bot-prod
    container_name: dexlot-bot-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: python main.py
    user: "1000:1000"
    restart: unless-stopped
    env_file: .env
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    extra_hosts:
      - "api.telegram.org=149.154.166.110"
      - "api.telegram.org=[2001:67c:4e8:f004::9]"
    ports:
      - "${DOCKER_IP}:${DOCKER_PORT}:8080"
    networks:
      - dexlot-bot-network-prod  

  dexlot-bot-redis-prod:
    image: redis:latest
    container_name: dexlot-bot-redis-prod
    volumes:
      - redis-data:/data
    restart: unless-stopped
    #user: "1000:1000"
    networks:
      - dexlot-bot-network-prod  

volumes:
    redis-data:

networks:
    dexlot-bot-network-prod:
        driver: bridge
