# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Develop

on:
  push:
    branches: [ "develop" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Deploy to Develop
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Get Current BRANCH NAME
       id: vars
       run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

     - name: Run command on remote server
       uses: appleboy/ssh-action@v1.0.0
       env:
          ENV: ${{vars.ENV_DEV}}
          APP_PATH: ${{vars.APP_PATH_DEV}}
          GIT_CRED: ${{secrets.GIT_CRED}}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
       with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          envs: ENV,APP_PATH,GIT_CRED,BRANCH_NAME
          script: |
            cd $APP_PATH
            cat <<< $ENV > .env
            cat <<< $GIT_CRED > git-credentials
            git fetch --all
            git reset --hard origin/$BRANCH_NAME
            git checkout $BRANCH_NAME
            chmod +x update.sh
            ./update.sh $BRANCH_NAME